---
title: "Code de conduite"
date: "2023-06-16T10:30:14"
lastmod: "2023-06-20T16:10:25"
---

== Code de conduite

=== Règlement de la communauté Developers Group Dijon et règles contre le harcèlement

Developers Group Dijon s’engage à offrir à tous les participant.e.s une expérience inclusive ne laissant aucune place au harcèlement, indépendamment de leur identité et expression de genre, orientation sexuelle, handicap, neurodiversité, apparence physique, corpulence, ethnicité, nationalité, race, âge, religion, ou de toute autre catégorie protégée. Nous ne tolérerons aucune forme de harcèlement à l’encontre des participants. Developers Group Dijon prend très au sérieux les cas de non-respect des règles et prendra les mesures appropriées.

=== Tou.te.s les participant.e.s aux événements Developers Group Dijon doivent respecter les règles suivantes:

*Soyez excellent.e.s les un.e.s envers les autres.*

Traitez les autres avec respect. Participez en reconnaissant que tout le monde mérite d’être ici, et chacun d’entre nous a le droit de profiter de son expérience sans crainte de harcèlement, de discrimination ni de consension, qu’elles soit flagrantes ou par micro-agressions. Les plaisanteries ne doivent pas dénigrer autrui. Réfléchissez à ce que vous dites et à ce que vous ressentiriez si c’était dit à vous ou à votre sujet.

*Parlez si vous voyez ou entendez quelque chose.*

Le harcèlement ne saurait être toléré, et vous avez le droit de réagir poliment si on manque de respect à votre égard ou à l’égard d’autrui. La personne qui vous met mal à l’aise n’a peut-être pas conscience du tort qu’elle cause. N’hésitez pas à évoquer poliment son comportement avec elle.

*Entraînez-vous à vous dire « Oui » et « mutuellement ».*

C’est une technique d’improvisation théâtrale qui vise à s’inspirer des idées des autres. Ensemble, nous profitons à tous.

=== Nous appliquons une politique de zéro tolérance pour tout type de harcèlement.

Les participant.e.s invité.e.s à cesser tout harcèlement doivent se mettre immédiatement en conformité. Notre politique de tolérance zéro signifie que nous prenons en compte et examinons tout cas présumé de non-respect du règlement de la communauté concernant les événements et des règles contre le harcèlement, et que nous y répondons de manière appropriée. Nous vous encourageons à signaler tout comportement qui vous met mal à l’aise ou qui vous inquiète, en vous rapprochant d’un membre du Developers Group Dijon ou en envoyant un e-mail à l’adresse developers.group.dijon@gmail.com.

Quiconque ayant un comportement inapproprié, harcelant ou mettant mal à l’aise ou s’il.elle ne respecte pas les présentes règles, peut être exclu.e à tout moment ou interdit.e d’admission (y compris à des événements Developers Group Dijon futurs) de tout événement organisé par Developers Group Dijon et à sa seule discrétion. Les personnes exclues d’un événement pour non-respect de cette règle ne recevront aucun remboursement.

Cela inclut (liste non exhaustive) :

* Persécuter/Suivre
* Intimidation délibérée
* Harcèlement ou enregistrement
* Perturbation continue des discussions ou autres événements
* Commentaires oraux choquants
* Langage verbal qui renforce les structures sociales de domination
* Images et langage à caractère sexuel dans les espaces publics
* Contact physique inapproprié
* Attention sexuelle ou physique indésirable

En lien à (liste non exhaustive) :

*  Neurodiversité
* Origine ethnique
* Couleur
* Nationalité
* Identité de genre
* Expression de genre
* Orientation sexuelle
* Âge
* Taille du corps
* Handicaps
* Apparence
* Religion
* Grossesse
